/**
 * The Decentraland L1 wearable set — GENERATED, do not hand-edit.
 *
 * Regenerate with:  node scripts/l1/build-l1-catalog.mjs
 *
 * collections-v1 lives on Ethereum mainnet and has been closed since 2021, so
 * this snapshot is stable by nature. It holds URNs and metadata only; the
 * separate static-pack build resolves those URNs into skeleton-free GLBs.
 *
 * Source: https://peer.decentraland.org/lambdas/collections
 * Fetched: 2026-08-18
 * 42 collections, 438 items.
 */

/** 0 = both body shapes, 1 = male representation only, 2 = female only. */
export type L1BodyMask = 0 | 1 | 2;

/** [itemSlug, name, category, rarity, bodyMask] */
export type L1CatalogItemTuple = readonly [string, string, string, string, L1BodyMask];

/** [collectionSlug, displayTitle, ethereumContractAddress, items] */
export type L1CatalogCollectionTuple = readonly [
  string,
  string,
  string,
  readonly L1CatalogItemTuple[],
];

export const L1_CATALOG_SOURCE = "https://peer.decentraland.org/lambdas/collections";
export const L1_CATALOG_FETCHED_AT = "2026-08-18";
export const L1_CATALOG_COLLECTION_COUNT = 42;
export const L1_CATALOG_ITEM_COUNT = 438;

/** Ordered largest collection first — the floor packer relies on that. */
export const L1_CATALOG_RAW: readonly L1CatalogCollectionTuple[] = [
  ["halloween_2019", "Halloween 2019", "0xc1f4b0eea2bd6690930e6c66efd3e197d620b9c2", [
      ["bee_suit_earring", "Bee Earrings", "earring", "epic", 2],
      ["bee_suit_top_head", "Bee Headband", "top_head", "epic", 2],
      ["bee_suit_upper_body", "Bee Suit", "upper_body", "epic", 2],
      ["bee_suit_lower_body", "Bee Suit Leggings", "lower_body", "epic", 2],
      ["bee_suit_feet", "Bee Suit Shoes", "feet", "epic", 2],
      ["bloody_knife_headband_top_head", "Bloody Knife", "top_head", "epic", 0],
      ["bride_of_frankie_hair", "Bride of Frankie Hair", "hair", "mythic", 2],
      ["bride_of_frankie_feet", "Bride of Frankie Shoes", "feet", "mythic", 2],
      ["bride_of_frankie_lower_body", "Bride of Frankie Skirt", "lower_body", "mythic", 2],
      ["bride_of_frankie_upper_body", "Bride of Frankie Suit", "upper_body", "mythic", 2],
      ["cat_mask", "Cat Mask", "mask", "legendary", 0],
      ["classic_top_hat", "Classic Top Hat", "hat", "epic", 0],
      ["creepy_nurse_hat", "Creepy Nurse Hat", "hat", "legendary", 2],
      ["creepy_nurse_upper_body", "Creepy Nurse Shirt", "upper_body", "legendary", 2],
      ["creepy_nurse_feet", "Creepy Nurse Shoes", "feet", "legendary", 2],
      ["creepy_nurse_lower_body", "Creepy Nurse Skirt", "lower_body", "legendary", 2],
      ["creepy_pumpkin_helmet", "Creepy Pumpkin", "helmet", "legendary", 0],
      ["cross_skull_mask", "Cross Skull", "mask", "mythic", 0],
      ["diamond_skull_mask", "Diamond Skull", "mask", "mythic", 0],
      ["floral_skull_mask", "Floral Skull", "mask", "legendary", 0],
      ["frankie_hat", "Frankie Hat", "hat", "legendary", 1],
      ["frankie_lower_body", "Frankie Pants", "lower_body", "legendary", 1],
      ["frankie_feet", "Frankie Shoes", "feet", "legendary", 1],
      ["frankie_upper_body", "Frankie Suit", "upper_body", "epic", 1],
      ["funny_skull_mask", "Funny Skull", "mask", "epic", 0],
      ["happy_pumpkin_helmet", "Happy Pumpkin", "helmet", "swanky", 0],
      ["jester_hair", "Jester Hair", "hair", "mythic", 2],
      ["jester_lower_body", "Jester Leggings", "lower_body", "mythic", 2],
      ["jester_mask", "Jester Mask", "mask", "mythic", 2],
      ["jester_feet", "Jester Shoes", "feet", "mythic", 2],
      ["jester_upper_body", "Jester Suit", "upper_body", "mythic", 2],
      ["jester_earring", "Jingle Bells Earrings", "earring", "mythic", 2],
      ["lirio_skull_mask", "Lirio Skull", "mask", "legendary", 0],
      ["machete_headband_top_head", "Machete Headband", "top_head", "legendary", 0],
      ["mariachi_hat", "Mariachi Hat", "hat", "swanky", 0],
      ["mexican_hat", "Mexican Hat", "hat", "epic", 0],
      ["monkey_skull_mask", "Monkey Skull", "mask", "epic", 0],
      ["muzzle_mask", "Muzzle Mask", "mask", "mythic", 0],
      ["spy_suit_hair", "Pony Tail Hair", "hair", "legendary", 2],
      ["rose_skull_mask", "Rose Skull", "mask", "legendary", 0],
      ["sad_clown_mask", "Sad Clown Mask", "mask", "epic", 1],
      ["sad_clown_lower_body", "Sad Clown Pants", "lower_body", "epic", 1],
      ["sad_clown_feet", "Sad Clown Shoes", "feet", "epic", 1],
      ["sad_clown_upper_body", "Sad Clown Suit", "upper_body", "epic", 1],
      ["skeleton_suit_upper_body", "Skeleton Suit", "upper_body", "mythic", 1],
      ["skeleton_suit_feet", "Skeleton Suit Feet", "feet", "mythic", 1],
      ["skeleton_suit_lower_body", "Skeleton Suit Pants", "lower_body", "mythic", 1],
      ["skeleton_suit_hat", "Skull Mexican Hat", "hat", "mythic", 1],
      ["bride_of_frankie_earring", "Spider Earrings", "earring", "mythic", 2],
      ["spy_suit_upper_body", "Spy Suit", "upper_body", "legendary", 2],
      ["spy_suit_eyewear", "Spy Suit Eyewear", "eyewear", "legendary", 2],
      ["spy_suit_lower_body", "Spy Suit Pants", "lower_body", "legendary", 2],
      ["spy_suit_feet", "Spy Suit Shoes", "feet", "legendary", 2],
      ["star_skull_mask", "Star Skull", "mask", "legendary", 0],
      ["trippy_skull_mask", "Trippy Skull", "mask", "mythic", 0],
      ["undead_pirate_helmet", "Undead Pirate Head", "helmet", "mythic", 1],
      ["undead_pirate_lower_body", "Undead Pirate Pants", "lower_body", "mythic", 1],
      ["undead_pirate_upper_body", "Undead Pirate Torso", "upper_body", "mythic", 1],
      ["vampire_hair", "Vampire Hair", "hair", "legendary", 1],
      ["vampire_lower_body", "Vampire Pants", "lower_body", "legendary", 1],
      ["vampire_feet", "Vampire Shoes", "feet", "legendary", 1],
      ["vampire_upper_body", "Vampire Suit", "upper_body", "legendary", 1],
      ["witch_hat", "Witch Hat", "hat", "epic", 2],
      ["witch_feet", "Witch Shoes", "feet", "epic", 2],
      ["witch_lower_body", "Witch Skirt", "lower_body", "epic", 2],
      ["witch_upper_body", "Witch Suit", "upper_body", "epic", 2],
      ["zombie_suit_feet", "Zombie Boots", "feet", "epic", 1],
      ["zombie_suit_mask", "Zombie Mask", "mask", "epic", 1],
      ["zombie_suit_upper_body", "Zombie Suit", "upper_body", "epic", 1],
      ["zombie_suit_lower_body", "Zombie Suit Pants", "lower_body", "epic", 1],
  ]],
  ["community_contest", "Community Contest", "0x32b7495895264ac9d0b12d32afd435453458b1c6", [
      ["cw_acornknitcap_hat", "Acorn Knit Cap", "hat", "legendary", 0],
      ["f_cw_astronaut_shoes_feet", "Astronaut Shoes", "feet", "mythic", 2],
      ["cw_aviator_coat_upper_body", "Aviator Coat", "upper_body", "mythic", 0],
      ["cw_aviator_googles_eyewear", "Aviator Goggles", "eyewear", "mythic", 0],
      ["cw_aviator_helmet_hat", "Aviator Helmet", "hat", "mythic", 0],
      ["cw_aviator_trousers_lower_body", "Aviator Trousers", "lower_body", "mythic", 0],
      ["cw_bell_attendant_hat", "Bell Attendant Hat", "hat", "legendary", 0],
      ["cw_bell_attendant_upper_body", "Bell Attendant Suit", "upper_body", "legendary", 0],
      ["cw_bell_attendant_lower_body", "Bell Attendant Trousers", "lower_body", "legendary", 0],
      ["cw_bitcoinglasses_eyewear", "Bitcoin Eyewear", "eyewear", "legendary", 0],
      ["cw_bluegarment_hat", "Blue Garment of Gratitude Hat", "hat", "legendary", 0],
      ["cw_bluegarment_lower_body", "Blue Garment of Gratitude Trousers", "lower_body", "legendary", 0],
      ["cw_bluegarment_upper_body", "Blue Pullover of Garment of Gratitude", "upper_body", "legendary", 0],
      ["cw_casinovisor_hat", "Casino Visor", "hat", "epic", 0],
      ["cw_city_sneakers_feet", "City Decentraland Sneakers", "feet", "epic", 0],
      ["m_cw_coat_of_wonder_upper_body", "Coat of Wonder", "upper_body", "mythic", 1],
      ["cw_cyberpunk_coat_upper_body", "CyberPunk Coat", "upper_body", "mythic", 0],
      ["cw_cyborg_monocle_eyewearraver", "Cyborg Monocle (It's over 9000!!!)", "eyewear", "mythic", 0],
      ["f_cw_astronaut_helmet_helmet", "Decentraland Astronaut Helmet", "helmet", "mythic", 2],
      ["f_cw_astronaut_pants_lower_body", "Decentraland Astronaut Pants", "lower_body", "mythic", 2],
      ["f_cw_astronaut_suit_upper_body", "Decentraland Astronaut Suit", "upper_body", "mythic", 2],
      ["cw_fox_top_head", "Fox Hat", "top_head", "mythic", 0],
      ["cw_greengarment_hat", "Green Garment of Gratitude Hat", "hat", "legendary", 0],
      ["cw_greengarment_lower_body", "Green Garment of Gratitude Trousers", "lower_body", "legendary", 0],
      ["cw_greengarment_upper_body", "Green Pullover of Garment of Gratitude", "upper_body", "legendary", 0],
      ["cw_hat_of_wonder_hat", "Hat of Wonder", "hat", "mythic", 1],
      ["cw_hazmat_shoes_feet", "Hazmat Shoes", "feet", "mythic", 0],
      ["cw_hazmat_suit_upper_body", "Hazmat Suit", "upper_body", "mythic", 0],
      ["cw_icecream_top_head", "Icecream Hat", "top_head", "mythic", 0],
      ["cw_foam_big_hat", "Mexican Foam Hat", "hat", "epic", 0],
      ["cw_monocle_eyewear", "Monocle Eyewear", "eyewear", "epic", 0],
      ["cw_native_american_tiara", "Native American Hat", "tiara", "mythic", 0],
      ["cw_neon_jacket_upper_body", "Neon Cool Jacket", "upper_body", "mythic", 0],
      ["cw_orangegarment_hat", "Orange Garment of Gratitude Hat", "hat", "legendary", 0],
      ["cw_orangegarment_lower_body", "Orange Garment of Gratitude Trousers", "lower_body", "legendary", 0],
      ["cw_orangegarment_upper_body", "Orange Pullover of Garment of Gratitude", "upper_body", "legendary", 0],
      ["cw_peacock_feather_earring", "Peacock Feather Earrings", "earring", "epic", 0],
      ["cw_pineapple_eyewear", "Pineapple Eyewear", "eyewear", "epic", 0],
      ["cw_raver_feet", "Raver Boots", "feet", "legendary", 0],
      ["cw_raver_eyewear", "Raver Googles", "eyewear", "legendary", 0],
      ["cw_raver_lower_body", "Raver Shorts", "lower_body", "legendary", 0],
      ["cw_raver_upper_body", "Raver Top", "upper_body", "legendary", 0],
      ["cw_rollers_feet", "Rollers", "feet", "mythic", 0],
      ["cw_shoes_of_wonder_feet", "Shoes of Wonder", "feet", "mythic", 0],
      ["cw_smiley_alien_hat", "Smiley Alien Hat", "hat", "legendary", 0],
      ["cw_hot_dog_top_head", "Sombrero de Hot Dog", "top_head", "legendary", 0],
      ["cw_trendy_sport_hat", "Trendy Sport  Hat", "hat", "mythic", 0],
      ["f_cw_trendy_pants_lower_body", "Trendy Sport Pants", "lower_body", "mythic", 2],
      ["m_cw_trendy_pants_lower_body", "Trendy Sport Pants", "lower_body", "mythic", 1],
      ["m_cw_trendy_sport_shoes_feet", "Trendy Sport Sandals", "feet", "mythic", 0],
      ["f_cw_trendy_sport_shoes_feet", "Trendy Sport Shoes", "feet", "mythic", 0],
      ["f_cw_trendy_jacket_upper_body", "Trendy Sportwear Jacket", "upper_body", "mythic", 2],
      ["m_cw_trendy_jacket_upper_body", "Trendy Sportwear Jacket", "upper_body", "mythic", 1],
      ["m_cw_pants_of_wonder_lower_body", "Trousers of Wonder", "lower_body", "mythic", 1],
      ["cw_tuxedo_tshirt_upper_body", "Tuxedo T Shirt", "upper_body", "epic", 0],
      ["cw_western_hat", "Western Hat", "hat", "epic", 0],
      ["cw_yellowgarment_hat", "Yellow Garment of Gratitude Hat", "hat", "legendary", 0],
      ["cw_yellowgarment_lower_body", "Yellow Garment of Gratitude Trousers", "lower_body", "legendary", 0],
      ["cw_yellowgarment_upper_body", "Yellow Pullover of Garment of Gratitude", "upper_body", "legendary", 0],
  ]],
  ["xmas_2019", "Christmas 2019", "0xc3af02c0fd486c8e9da5788b915d6fff3f049866", [
      ["8bit_sweater_upper_body", "8 Bit Christmas Sweater", "upper_body", "mythic", 0],
      ["xmas_ball_earring", "Christmas Ball Earring", "earring", "epic", 0],
      ["xmas_blue_hat", "Christmas Blue Hat", "hat", "epic", 0],
      ["xmas_cyberpunk_eyewear", "Christmas CyberPunk Eyewear", "eyewear", "epic", 0],
      ["xmas_elf_hat", "Christmas Elf Hat", "hat", "epic", 0],
      ["xmas_elf_feet", "Christmas Elf Shoes", "feet", "mythic", 0],
      ["xmas_green_hat", "Christmas Green Hat", "hat", "epic", 0],
      ["xmas_light_ball_earring", "Christmas Light Ball Earring", "earring", "epic", 0],
      ["xmas_light_tree_earring", "Christmas Light Tree Earring", "earring", "epic", 0],
      ["cyber_xmas_eyewear", "Christmas Neon Eyewear", "eyewear", "mythic", 0],
      ["xmas_red_hat", "Christmas Red Hat", "hat", "epic", 0],
      ["xmas_reindeer_hat", "Christmas Reindeer Hat", "hat", "mythic", 0],
      ["xmas_ski_eyewear", "Christmas Ski Eyewear", "eyewear", "mythic", 0],
      ["xmas_sockets_feet", "Christmas Sockets", "feet", "mythic", 0],
      ["xmas_tree_eyewear", "Christmas Tree Eyewear", "eyewear", "mythic", 0],
      ["xmas_yellow_hat", "Christmas Yellow Hat", "hat", "epic", 0],
      ["f_cyber_suit_lower_body", "Cyber Pants", "lower_body", "mythic", 2],
      ["m_cyber_suit_lower_body", "Cyber Pants", "lower_body", "mythic", 1],
      ["f_cyber_suit_upper_body", "Cyber Suit", "upper_body", "mythic", 2],
      ["m_cyber_suit_upper_body", "Cyber Suit", "upper_body", "mythic", 1],
      ["f_cyber_xmas_helmet", "Cyber Xmas Helmet", "helmet", "mythic", 2],
      ["m_cyber_xmas_helmet", "Cyber Xmas Helmet", "helmet", "mythic", 1],
      ["xmas_cyberpunk_upper_body", "Cyberpunk Jacket", "upper_body", "mythic", 1],
      ["f_led_suit_lower_body", "Led Pants", "lower_body", "mythic", 2],
      ["m_led_suit_lower_body", "Led Pants", "lower_body", "mythic", 1],
      ["f_led_suit_upper_body", "Led Suit", "upper_body", "mythic", 2],
      ["m_led_suit_upper_body", "Led Suit", "upper_body", "mythic", 1],
      ["pixel_sweater_upper_body", "Pixel Christmas Sweater", "upper_body", "mythic", 0],
      ["santa_facial_hair", "Santa Beard", "facial_hair", "mythic", 1],
      ["sledge_sockets_feet", "Sledge Shoes", "feet", "mythic", 0],
      ["snowflake_earring", "Snowflake Earrings", "earring", "epic", 0],
      ["xmas_snowman_helmet", "Snowman Head", "helmet", "mythic", 0],
  ]],
  ["moonshot_2020", "Moonshot 2020", "0x6a99abebb48819d2abe92c5e4dc4f48dc09a3ee8", [
      ["ms_axiegg_upper_body", "AxieGG Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_battleracers_upper_body", "Battle Racers Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_bullionix_upper_body", "Bullionix Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_cent_upper_body", "Cent Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_crucible_upper_body", "Crucible Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_dclcore_upper_body", "DCL Core Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_dclplazas_upper_body", "DCL Plazas Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_decentralgames_upper_body", "Decentral Games Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_dcl_upper_body", "Decentraland Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_ethermon_upper_body", "Ethermon Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_gamecredits_upper_body", "Game Credits Soccer T-Shirt", "upper_body", "legendary", 0],
      ["moonshot_2020_golden_boots_feet", "Golden Boots - MoonShot 2020", "feet", "unique", 0],
      ["ms_knownorigin_upper_body", "Known Origin Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_matic_upper_body", "Matic Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_metafactory_upper_body", "MetaFactory Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_metazone_upper_body", "MetaZone Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_mintbase_upper_body", "Mintbase Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_neighbourhood_upper_body", "Neighbourhood Project Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_nonfungible_upper_body", "NonFungible Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_opensea_upper_body", "OpenSea Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_pixelchain_upper_body", "Pixelchain Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_pm_upper_body", "Polygonal Mind Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_sorare_upper_body", "Sorare Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_superare_upper_body", "SuperRare Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_vegascity_upper_body", "Vegas City Soccer T-Shirt", "upper_body", "legendary", 0],
      ["ms_whale_upper_body", "Whale Soccer T-Shirt", "upper_body", "legendary", 0],
  ]],
  ["dcl_launch", "Decentraland Launch", "0xd35147be6401dcb20811f2104c33de8e97ed6818", [
      ["m_barbarian_upper_body", "Barbarian Chest Piece", "upper_body", "mythic", 1],
      ["m_barbarian_helmet_hat", "Barbarian Helmet", "hat", "mythic", 1],
      ["m_barbarian_feet", "Barbarian Shoes", "feet", "mythic", 1],
      ["m_barbarian_lower_body", "Barbarian Trousers", "lower_body", "mythic", 1],
      ["colorful_hat_hat", "Colorful Hat", "hat", "epic", 0],
      ["dcl_hat_hat", "Decentraland Hat", "hat", "rare", 0],
      ["dcl_hoodie_upper_body", "Decentraland Hoodie", "upper_body", "rare", 0],
      ["launch_tshirt_upper_body", "Decentraland Launch T-Shirt", "upper_body", "rare", 0],
      ["dcl_earrings_earring", "Decentraland Logo Earrings", "earring", "rare", 0],
      ["dcl_tshirt_upper_body", "Decentraland T-Shirt", "upper_body", "uncommon", 0],
      ["dcl_mana_earring", "MANA Earrings", "earring", "epic", 0],
      ["mana_eyewear", "MANA Eyewear", "eyewear", "legendary", 0],
      ["mana_hat", "MANA Hat", "hat", "rare", 0],
      ["mana_hoodie_upper_body", "MANA Hoodie", "upper_body", "rare", 0],
      ["mana_tshirt_upper_body", "MANA T-Shirt", "upper_body", "rare", 0],
      ["razor_blade_eyewear", "Razor Blade Eyewear", "eyewear", "mythic", 0],
      ["razor_blade_upper_body", "Razor Blade Jacket", "upper_body", "mythic", 0],
      ["razor_blade_feet", "Razor Blade Shoes", "feet", "mythic", 0],
      ["razor_blade_lower_body", "Razor Blade Trousers", "lower_body", "mythic", 0],
      ["umbrella_hat", "Umbrella Hat", "hat", "epic", 0],
  ]],
  ["halloween_2020", "Halloween 2020", "0xfeb52cbf71b9adac957c6f948a6cf9980ac8c907", [
      ["hwn_2020_cat_eyes", "Cat Eyes - Halloween 2020", "eyes", "uncommon", 0],
      ["hwn_2020_creepy_mouth", "Creepy Mouth - Halloween 2020", "mouth", "uncommon", 0],
      ["hwn_2020_ddlm_01_eyes", "Dia de los Muertos Eyes - Halloween 2020", "eyes", "epic", 0],
      ["hwn_2020_ddlm_03_eyes", "Dia de los Muertos Flower Eyes - Halloween 2020", "eyes", "legendary", 0],
      ["hwn_2020_ddlm_mouth", "Dia de los Muertos Mouth - Halloween 2020", "mouth", "legendary", 0],
      ["hwn_2020_ddlm_02_eyes", "Dia de los Muertos Skull Eyes - Halloween 2020", "eyes", "legendary", 0],
      ["hwn_2020_dracula_mouth", "Dracula Mouth - Halloween 2020", "mouth", "legendary", 0],
      ["hwn_2020_cult_servant_feet", "Evil Cult Servant Boots - Halloween 2020", "feet", "epic", 0],
      ["hwn_2020_cult_supreme_feet", "Evil Cult Supreme Boots - Halloween 2020", "feet", "mythic", 0],
      ["hwn_2020_ghostblaster_tiara", "GhostBlaster NightVision Device", "tiara", "epic", 0],
      ["hwn_2020_ghostblaster_lower_body", "GhostBlaster Pants - Halloween 2020", "lower_body", "epic", 0],
      ["hwn_2020_ghostblaster_upper_body", "GhostBlaster Suit - Halloween 2020", "upper_body", "epic", 0],
      ["hwn_2020_cult_servant_helmet", "Helmet of Servant of Evil Cult", "helmet", "epic", 0],
      ["hwn_2020_cult_supreme_helmet", "Helmet of Supreme of Evil Cult", "helmet", "mythic", 0],
      ["hwn_2020_cult_servant_lower_body", "Pants of Servant of Evil Cult - Halloween 2020", "lower_body", "epic", 0],
      ["hwn_2020_cult_supreme_lower_body", "Pants of Supreme of Evil Cult - Halloween 2020", "lower_body", "mythic", 0],
      ["hwn_2020_pumpkin_mouth", "Pumpkin Mouth - Halloween 2020", "mouth", "epic", 0],
      ["hwn_2020_cult_servant_upper_body", "Servant of Evil Cult Suit- Halloween 2020", "upper_body", "epic", 0],
      ["hwn_2020_cult_supreme_upper_body", "Supreme of Evil Cult Suit - Halloween 2020", "upper_body", "mythic", 0],
  ]],
  ["mch_collection", "MCH Collection", "0xf64dc33a192e056bb5f0e5049356a0498b502d50", [
      ["mch_caocao_upper_body", "Caocao T-Shirt", "upper_body", "epic", 0],
      ["mch_cleopatra_upper_body", "Cleopatra T-Shirt", "upper_body", "epic", 0],
      ["mch_fukuzawa_upper_body", "Fukuzawa T-Shirt", "upper_body", "epic", 0],
      ["mch_georgewashington_upper_body", "George Washington T-Shirt", "upper_body", "epic", 0],
      ["mch_gennnaihiraga_upper_body", "Hiraga Gennai T-Shirt", "upper_body", "epic", 0],
      ["mch_huangzhong_upper_body", "Huang Zhong T-Shirt", "upper_body", "epic", 0],
      ["mch_kingarthur_upper_body", "King Arthur T-Shirt", "upper_body", "epic", 0],
      ["mch_leodavinci_upper_body", "Leonardo Da Vinci T-Shirt", "upper_body", "epic", 0],
      ["mch_enemy_upper_body", "MCH Rare Enemy T-Shirt", "upper_body", "epic", 0],
      ["mch_napoleon_upper_body", "Napoleon T-Shirt", "upper_body", "epic", 0],
      ["mch_nightingale_upper_body", "Nightingale T-Shirt", "upper_body", "epic", 0],
      ["mch_nobunagaoda_upper_body", "Nobunaga Oda T-Shirt", "upper_body", "epic", 0],
      ["mch_pascal_upper_body", "Pascal T-Shirt", "upper_body", "epic", 0],
      ["mch_spartacs_upper_body", "Spartacs T-Shirt", "upper_body", "epic", 0],
      ["mch_wrightbrother_upper_body", "Wright Brothers T-Shirt", "upper_body", "epic", 0],
  ]],
  ["xmas_2020", "Christmas 2020", "0xecf073f91101ce5628669c487aee8f5822a101b1", [
      ["btc_xmas_sweater_upper_body", "Bitcoin Christmas Sweater", "upper_body", "legendary", 0],
      ["blue_jacket_xmas_upper_body", "Blue Winter Jacket", "upper_body", "epic", 0],
      ["santa_xmas_2020_hat", "Christmas Santa Hat", "hat", "epic", 0],
      ["covinch_xmas_mask", "Covinch Christmas Mask", "mask", "mythic", 0],
      ["doge_xmas_tshirt_upper_body", "Dogecoin T Shirt", "upper_body", "legendary", 0],
      ["eth_xmas_sweater_upper_body", "Ethereum Christmas Sweater", "upper_body", "legendary", 0],
      ["mana_xmas_sweater_upper_body", "MANA Christmas Sweater", "upper_body", "legendary", 0],
      ["red_jacket_xmas_upper_body", "Red Winter Jacket", "upper_body", "legendary", 0],
      ["santa_xmas_mask", "santa Christmas Mask", "mask", "mythic", 0],
      ["santa_xmas_2020_upper_body", "Santa Christmas Suit", "upper_body", "epic", 0],
      ["yellow_jacket_xmas_upper_body", "Yellow Winter Jacket", "upper_body", "legendary", 0],
  ]],
  ["atari_launch", "Atari Launch", "0x4c290f486bae507719c562b6b524bdb71a2570c9", [
      ["atari_blue_hat", "Blue Atari Cap", "hat", "epic", 0],
      ["atari_blue_upper_body", "Blue Atari Tee", "upper_body", "epic", 0],
      ["atari_green_hat", "Green Atari Cap", "hat", "epic", 0],
      ["atari_green_upper_body", "Green Atari Tee", "upper_body", "epic", 0],
      ["atari_orange_hat", "Orange Atari Cap", "hat", "epic", 0],
      ["atari_orange_upper_body", "Orange Atari Tee", "upper_body", "epic", 0],
      ["atari_purple_hat", "Purple Atari Cap", "hat", "epic", 0],
      ["atari_purple_upper_body", "Purple Atari Tee", "upper_body", "epic", 0],
      ["atari_red_hat", "Red Atari Cap", "hat", "epic", 0],
      ["atari_red_upper_body", "Red Atari Tee", "upper_body", "epic", 0],
  ]],
  ["exclusive_masks", "Exclusive Masks", "0xc04528c14c8ffd84c7c1fb6719b4a89853035cdd", [
      ["asian_fox", "Asian Fox Mask", "mask", "legendary", 0],
      ["bird_mask", "Bird Mask", "mask", "legendary", 0],
      ["classic_mask", "Classic Mask", "mask", "legendary", 0],
      ["clown_nose", "Clown Nose", "mask", "legendary", 0],
      ["killer_mask", "Killer Mask", "mask", "legendary", 0],
      ["serial_killer_mask", "Serial Killer Mask", "mask", "legendary", 0],
      ["theater_mask", "Theater", "mask", "legendary", 0],
      ["tropical_mask", "Tropical Mask", "mask", "legendary", 0],
  ]],
  ["stay_safe", "Stay Safe", "0x201c3af8c471e5842428b74d1e7c0249adda2a92", [
      ["protection_mask_abstract_mask", "Abstract Protection Mask", "mask", "epic", 0],
      ["protection_mask_african_mask", "African Protection Mask", "mask", "epic", 0],
      ["protection_mask_funny_mask", "Funny Protection Mask", "mask", "epic", 0],
      ["protection_mask_graffiti_mask", "Graffiti Protection Mask", "mask", "epic", 0],
      ["protection_mask_hot_mask", "Hot Protection Mask", "mask", "epic", 0],
      ["protection_mask_monster_mask", "Monster Protection Mask", "mask", "epic", 0],
      ["protection_mask_skull_mask", "Skull Protection Mask", "mask", "epic", 0],
      ["protection_mask_tiger_mask", "Tiger Protection Mask", "mask", "epic", 0],
  ]],
  ["3lau_basics", "3LAU Basics", "0xe1ecb4e5130f493551c7d6df96ad19e5b431a0a9", [
      ["3lau_blue_hat", "3LAU Blue Triangle Cap", "hat", "legendary", 0],
      ["3lau_hoodie_b_upper_body", "3LAU Blue Triangle Hoodie", "upper_body", "legendary", 0],
      ["3lau_tshirt_b_upper_body", "3LAU Blue Triangle Tee", "upper_body", "legendary", 0],
      ["3lau_white_hat", "3LAU White Triangle Cap", "hat", "epic", 0],
      ["3lau_hoodie_w_upper_body", "3LAU White Triangle Hoodie", "upper_body", "epic", 0],
      ["3lau_tshirt_w_upper_body", "3LAU White Triangle Tee", "upper_body", "epic", 0],
  ]],
  ["china_flying", "China Flying", "0x90958d4531258ca11d18396d4174a007edbc2b42", [
      ["china_flying_clothes_male", "China flying boyClothes", "upper_body", "legendary", 1],
      ["china_flying_hair_male", "China flying boyHair", "hair", "legendary", 1],
      ["china_flying_clothes_female", "China flying clothes", "upper_body", "legendary", 2],
      ["china_flying_hair_female", "China flying hair", "hair", "legendary", 2],
      ["china_flying_pants", "China flying pants", "lower_body", "legendary", 1],
      ["china_flying_skirt", "China flying skirt", "lower_body", "legendary", 2],
  ]],
  ["cybermike_cybersoldier_set", "CyberMike CyberSoldier", "0x24d538a6265b006d4b53c45ba91af5ef60dca6cb", [
      ["cybersoldier_gas_mask", "CYBERSOLDIER GAS MASK - Winter Soldier Collection - FROM CYBERMIKE", "mask", "mythic", 0],
      ["cybersoldier_boots_feet", "CYBERSOLDIER HASTE BOOTS - Winter Soldier Collection - Mark III - FROM CYBERMIKE", "feet", "mythic", 0],
      ["cybersoldier_helmet", "CYBERSOLDIER HELMET - Winter Soldier Collection - Mark III - FROM CYBERMIKE", "helmet", "mythic", 0],
      ["cybersoldier_leggings_lower_body", "CYBERSOLDIER LEGGINGS - Winter Soldier Collection - Mark III - FROM CYBERMIKE", "lower_body", "mythic", 0],
      ["cybersoldier_nightvision_eyewear", "CYBERSOLDIER NIGHT VISION GOGGLES - Winter Soldier Collection - FROM CYBERMIKE", "eyewear", "mythic", 0],
      ["cybersoldier_torso_upper_body", "CYBERSOLDIER TORSO - Winter Soldier Collection - Mark III - FROM CYBERMIKE", "upper_body", "mythic", 0],
  ]],
  ["cz_mercenary_mtz", "CZ Mercenary MTZ", "0xc3ca6c364b854fd0a653a43f8344f8c22ddfdd26", [
      ["aero_guard_mask", "Aero Guard", "mask", "legendary", 0],
      ["exo_blades_top_head", "Exo-blades", "top_head", "legendary", 0],
      ["exo_suit_upper_body", "Exo-Suit", "upper_body", "legendary", 0],
      ["holo_display_eyewear", "Holo Display", "eyewear", "legendary", 0],
      ["open_source_helmet", "Open Source", "helmet", "legendary", 0],
      ["regen_aura_top_head", "Regen Aura", "top_head", "legendary", 0],
  ]],
  ["dappcraft_moonminer", "Dappcraft Moonminer", "0x1e1d4e6262787c8a8783a37fee698bd42aa42bec", [
      ["moonminer_boots_feet", "DappCraft Moon Miner Boots", "feet", "legendary", 0],
      ["moonminer_goggles_eyewear", "DappCraft Moon Miner Goggles", "eyewear", "legendary", 0],
      ["moonminer_helmet", "DappCraft Moon Miner Helmet", "hat", "legendary", 0],
      ["moonminer_jacket_upper_body", "DappCraft Moon Miner Jacket", "upper_body", "legendary", 0],
      ["moonminer_neurahairs_hair", "DappCraft Moon Miner Neurahairs", "hair", "legendary", 0],
      ["moonminer_pants_lower_body", "DappCraft Moon Miner Trousers", "lower_body", "legendary", 0],
  ]],
  ["dc_meta", "DCMeta", "0xe7a64f6a239ed7f5bf18caa1ce2920d0c1278129", [
      ["meta_feet", "DC META 01000001", "feet", "mythic", 0],
      ["meta_helmet", "DC META 01000011", "helmet", "mythic", 0],
      ["meta_hair", "DC META 01000100", "hair", "mythic", 0],
      ["meta_upper_body", "DC META 01000101", "upper_body", "mythic", 0],
      ["meta_tiara", "DC META 01001101", "tiara", "mythic", 0],
      ["meta_lower_body", "DC META 01010100", "lower_body", "mythic", 0],
  ]],
  ["dc_niftyblocksmith", "Nifty Blocksmith", "0x102daabd1e9d294d4436ec4c521dce7b1f15499e", [
      ["blocksmith_feet", "DC Nifty Blocksmith Boots", "feet", "legendary", 0],
      ["blocksmith_eyewear", "DC Nifty Blocksmith Diamantex", "eyewear", "legendary", 0],
      ["blocksmith_top_head", "DC Nifty Blocksmith Drone", "top_head", "legendary", 0],
      ["blocksmith_helmet", "DC Nifty Blocksmith Helmet", "helmet", "legendary", 0],
      ["blocksmith_upper_body", "DC Nifty Blocksmith Jacket", "upper_body", "legendary", 0],
      ["blocksmith_lower_body", "DC Nifty Blocksmith Trousers", "lower_body", "legendary", 0],
  ]],
  ["dg_fall_2020", "Decentral Games Fall 2020", "0x7038e9d2c6f5f84469a84cf9bc5f4909bb6ac5e0", [
      ["dg_dress_shoes_feet", "Dress Shoes", "feet", "mythic", 0],
      ["dg_money_shades_eyewear", "Money Shades glasses", "eyewear", "mythic", 0],
      ["dg_robe_upper_body", "Robe", "upper_body", "mythic", 0],
      ["dg_kicks_feet", "Shoes", "feet", "mythic", 0],
      ["dg_suit_bottom_lower_body", "Suit bottom", "lower_body", "mythic", 0],
      ["dg_suit_top_upper_body", "Suit Top", "upper_body", "mythic", 0],
  ]],
  ["dg_summer_2020", "Decentral Games Summer 2020", "0xbf53c33235cbfc22cef5a61a83484b86342679c5", [
      ["dg_deezys_feet", "DG Deezys", "feet", "legendary", 0],
      ["dg_flip_up_spectacles_eyewear", "DG Flip Up Spectacles", "eyewear", "legendary", 0],
      ["dg_mink_fur_coat_upper_body", "DG Fur Mink", "upper_body", "legendary", 0],
      ["dg_slides_feet", "DG Slides", "feet", "legendary", 0],
      ["dg_tracksuit_bottom_lower_body", "DG Tracksuit Bottom", "lower_body", "legendary", 0],
      ["dg_tracksuit_top_upper_body", "DG Tracksuit Top", "upper_body", "legendary", 0],
  ]],
  ["dgtble_headspace", "Digitable Headspace", "0x574f64ac2e7215cba9752b85fc73030f35166bc0", [
      ["dgtble_dress_folife_upper_body", "The Headspace Flower of Life Dress", "upper_body", "legendary", 2],
      ["dgtble_shorts_folife_lower_body", "The Headspace Flower of Life Shorts", "lower_body", "legendary", 1],
      ["dgtble_hoodi_linetang_upper_body", "The Headspace Linetangles Hoodie", "upper_body", "legendary", 1],
      ["dgtble_protection_mask_dala_mask", "The Headspace Mandala Love Mask", "mask", "legendary", 0],
      ["dgtble_rainbow_grid_shoes_feet", "The Headspace Rainbow Grid Shoes", "feet", "legendary", 0],
      ["dgtble_tshirt_message_upper_body", "The Headspace The Messanger T-Shirt", "upper_body", "legendary", 1],
  ]],
  ["digital_alchemy", "Digital Alchemy", "0x5cf39e64392c615fd8086838883958752a11b486", [
      ["da_atomic_earring", "Digital Alchemy Atomic Earring", "earring", "legendary", 0],
      ["da_baggy_pants_lower_body", "Digital Alchemy Baggy Pants", "lower_body", "legendary", 0],
      ["da_dichroic_eyewear", "Digital Alchemy Dichroic Monocle", "eyewear", "legendary", 0],
      ["da_coat_upper_body", "Digital Alchemy Disruptive Coat", "upper_body", "legendary", 0],
      ["da_iridescent_hair", "Digital Alchemy Iridescent Hair", "hair", "legendary", 0],
      ["da_rock_boots_feet", "Digital Alchemy Rock Boots", "feet", "legendary", 0],
  ]],
  ["ethermon_wearables", "Ethermon", "0x54266bcf2ffa841af934f003d144957d5934f3ab", [
      ["barkindle_top_head", "Barkindle Wearable", "top_head", "legendary", 0],
      ["ethermon_hat", "Ethermon Hat", "hat", "legendary", 0],
      ["ethermon_upper_body", "Ethermon Jacket", "upper_body", "legendary", 0],
      ["ethermon_lower_body", "Ethermon Pants", "lower_body", "legendary", 0],
      ["ethermon_feet", "Ethermon Shoes", "feet", "legendary", 0],
      ["ruffski_top_head", "Ruffski Wearable", "top_head", "legendary", 0],
  ]],
  ["mf_sammichgamer", "Sammich Gamer", "0x30d3387ff3de2a21bef7032f82d00ff7739e403c", [
      ["mf_animehair", "Anime warrior hair", "hair", "legendary", 0],
      ["mf_frogfins", "Frog fins", "feet", "legendary", 0],
      ["mf_sammichtorso", "Sammich frog outfit", "upper_body", "legendary", 0],
      ["mf_unicornpants", "Unicorn pants", "lower_body", "legendary", 0],
      ["mf_unicornhelmet", "Unicorn skate helmet", "helmet", "legendary", 0],
      ["mf_wingsneakers", "Wing sneakers", "feet", "legendary", 0],
  ]],
  ["ml_pekingopera", "MetaLand Peking Opera", "0x60d8271c501501c4b8cd9ed5343ac59d1b79d993", [
      ["jing_upper_body", "Peking Opera Jing Coat", "upper_body", "legendary", 0],
      ["jing_hat", "Peking Opera Jing Hat", "hat", "legendary", 0],
      ["jing_lower_body", "Peking Opera Jing Pants", "lower_body", "legendary", 0],
      ["jing_feet", "Peking Opera Jing Shoes", "feet", "legendary", 0],
      ["jing_xiangyu_mask", "Peking Opera Xiang Yu Mask", "mask", "legendary", 0],
      ["jing_yingbu_mask", "Peking Opera Ying Bu Mask", "mask", "legendary", 0],
  ]],
  ["pm_dreamverse_eminence", "Dreamverse Eminence", "0x09305998a531fade369ebe30adf868c96a34e813", [
      ["pm_dreamverse_eminence_pants", "Dream Bourgeois Breeches", "lower_body", "mythic", 0],
      ["pm_dreamverse_eminence_jacket", "Dream Oracle Jacket", "upper_body", "mythic", 0],
      ["pm_dreamverse_eminence_boots", "Ethereal Dreamer Boots", "feet", "mythic", 0],
      ["pm_dreamverse_eminence_cap", "Ethereal Sage Hat", "hat", "mythic", 0],
      ["pm_dreamverse_eminence_sweater", "Lucid Meditation Tunic", "upper_body", "mythic", 0],
      ["pm_dreamverse_eminence_hat_visor", "Lucid Visionary Crown", "hat", "mythic", 0],
  ]],
  ["pm_outtathisworld", "Outta This World", "0x75a3752579dc2d63ca229eebbe3537fbabf85a12", [
      ["pm_col1_alien_helmet", "Alien Helmet", "helmet", "legendary", 0],
      ["pm_col1_cat_helmet", "Cat Helmet", "helmet", "legendary", 0],
      ["pm_col1_dino_helmet", "Dino Helmet", "helmet", "legendary", 0],
      ["pm_col1_panda_helmet", "Panda Helmet", "helmet", "legendary", 0],
      ["pm_col1_cargo_pants_lower_body", "Polygonal Mind - Cargo Pants", "lower_body", "legendary", 0],
      ["pm_col1_trendy_coat_upper_body", "Polygonal Mind - Trendy Coat", "upper_body", "legendary", 0],
  ]],
  ["release_the_kraken", "Release the Kraken", "0xffc5043d9a00865d089d5eefa5b3d1625aec6763", [
      ["kraken_mythic_hat", "Kraken Cyborg Crown", "hat", "mythic", 0],
      ["kraken_legendary_hat", "Kraken Gold-Eye Crown", "hat", "legendary", 0],
      ["kraken_hat", "Kraken Hat", "hat", "uncommon", 0],
      ["kraken_hoodie_upper_body", "Kraken Hoodie", "upper_body", "uncommon", 0],
      ["kraken_epic_hat", "Kraken Ruby-Eye Crown", "hat", "epic", 0],
      ["kraken_tshirt_upper_body", "Kraken T-Shirt", "upper_body", "uncommon", 0],
  ]],
  ["sugarclub_yumi", "SugarClub Yumi", "0xb5d14052d1e2bce2a2d7459d0379256e632b855d", [
      ["yumi_glitter_eyes", "Yumi Glitter Eyes", "eyes", "legendary", 0],
      ["yumi_glitter_jacket_upper_body", "Yumi Glitter Jacket", "upper_body", "legendary", 0],
      ["yumi_glitter_leggings_lower_body", "Yumi Glitter Leggings", "lower_body", "legendary", 0],
      ["yumi_neon_boots_feet", "Yumi Neon Boots", "feet", "legendary", 0],
      ["yumi_neon_hair", "Yumi Neon Hair", "hair", "legendary", 0],
      ["yumi_retro_shades_eyewear", "Yumi Retro Shades", "eyewear", "legendary", 0],
  ]],
  ["tech_tribal_marc0matic", "Tech Tribal by Marc0matic", "0x480a0f4e360e8964e68858dd231c2922f1df45ef", [
      ["techtribal_beast_mask", "Tech Tribal Beast Mask", "mask", "legendary", 0],
      ["techtribal_bird_mask", "Tech Tribal Bird Mask", "mask", "legendary", 0],
      ["techtribal_shaman_garb", "Tech Tribal Shaman Garb", "upper_body", "legendary", 0],
      ["techtribal_shoes", "Tech Tribal Shoes", "feet", "legendary", 0],
      ["techtribal_solar_garb", "Tech Tribal Solar Garb", "upper_body", "legendary", 0],
      ["tech_tribal_trousers", "Tech Tribal Trousers", "lower_body", "legendary", 0],
  ]],
  ["wonderzone_meteorchaser", "WonderZone Meteorchaser", "0x34ed0aa248f60f54dd32fbc9883d6137a491f4f3", [
      ["meteorchaser_transmitter_earring", "Meteorchaser transmitters", "earring", "legendary", 0],
      ["meteorite_dustmask_mask", "Meteorite dustmask", "mask", "legendary", 0],
      ["meteorite_protective_hardhat_hat", "Meteorite protective hardhat", "hat", "legendary", 0],
      ["meteorchaser_shoes_feet", "Shoes of the meteorchaser", "feet", "legendary", 0],
      ["meteorchaser_trousers_lower_body", "Trousers of the meteorchaser", "lower_body", "legendary", 0],
      ["meteorchaser_vest_upper_body", "Vest of the Meteorchaser", "upper_body", "legendary", 0],
  ]],
  ["wonderzone_steampunk", "WonderZone Steampunk", "0xb96697fa4a3361ba35b774a42c58daccaad1b8e1", [
      ["steampunk_boots", "Steampunk Boots", "feet", "legendary", 0],
      ["steampunk_goggles", "Steampunk Goggles", "eyewear", "legendary", 0],
      ["steampunk_jacket", "Steampunk Jacket", "upper_body", "legendary", 0],
      ["steampunk_mask", "Steampunk mask", "mask", "legendary", 0],
      ["steampunk_hat", "Steampunk Top Hat", "hat", "legendary", 0],
      ["steampunk_trousers", "Steampunks jodhpur trousers", "lower_body", "legendary", 0],
  ]],
  ["wz_wonderbot", "WonderBot", "0x5df4602e7f38a91ea7724fc167f0c67f61604b1e", [
      ["wz_wonderbot_torso", "Wonderbot Chestpiece", "upper_body", "mythic", 0],
      ["wz_wonderbot_feet", "Wonderbot Feet", "feet", "mythic", 0],
      ["wz_wonderbot_goggles", "Wonderbot goggles", "eyewear", "mythic", 0],
      ["wz_wonderbot_head", "Wonderbot Head", "helmet", "mythic", 0],
      ["wz_wonderbot_legs", "Wonderbot Legs", "lower_body", "mythic", 0],
      ["wz_wonderbot_hat", "Wonderbot Tricorn Hat", "top_head", "mythic", 0],
  ]],
  ["xmash_up_2020", "Xmash Up 2020", "0xdd9c7bc159dacb19c9f6b9d7e23948c87aa2397f", [
      ["xmash_up_googles_eyewear", "Bryfocals - Guest Artists Collection", "eyewear", "mythic", 0],
      ["xmash_up_boots_feet", "FEWO CLOUD SHOES - Guest Artists Collection", "feet", "mythic", 0],
      ["xmash_up_coat_upper_body", "Infinity Cow Coat - Guest Artists Collection", "upper_body", "mythic", 0],
      ["xmash_up_pants_lower_body", "Joelle Pants", "lower_body", "mythic", 0],
      ["xmash_up_cap_hat", "The Delbo Comic Cap - Guest Artists Collection", "hat", "mythic", 0],
  ]],
  ["dcg_collection", "DCG Collection", "0x3163d2cfee3183f9874e2869942cc62649eeb004", [
      ["dcg_black_hoodie_upper_body", "DCG Black Hoodie", "upper_body", "legendary", 0],
      ["dcg_black_tshirt_upper_body", "DCG Black T Shirt", "upper_body", "legendary", 0],
      ["dcg_white_hoodie_upper_body", "DCG White Hoodie", "upper_body", "legendary", 0],
      ["dcg_white_tshirt_upper_body", "DCG White T Shirt", "upper_body", "legendary", 0],
  ]],
  ["meme_dontbuythis", "Meme — Don't Buy This", "0x1a57f6afc902d25792c53b8f19b7e17ef84222d5", [
      ["meme_suit_pineapple", "Cool Pineapple Suit", "upper_body", "epic", 0],
      ["meme_pants_pineapple", "Fresh Pineapple Pants", "lower_body", "epic", 0],
      ["meme_suit_pineapple_onesie", "Sweet Pineapple Onesie", "upper_body", "epic", 0],
      ["meme_helmet_pineapple", "Tasty Pineapple Head", "helmet", "epic", 0],
  ]],
  ["ml_liondance", "MetaLand Lion Dance", "0x0b1c6c75d511fae05e7dc696f4cf14129a9c43c9", [
      ["lion_dance_upper_body", "Lion Dance Coat", "upper_body", "epic", 0],
      ["lion_dance_hat", "Lion Dance Hat", "hat", "epic", 0],
      ["lion_dance_lower_body", "Lion Dance Pants", "lower_body", "epic", 0],
      ["lion_dance_feet", "Lion Dance Shoes", "feet", "epic", 0],
  ]],
  ["rac_basics", "RAC Basics", "", [
      ["rac_hat", "RAC Cap", "hat", "unique", 0],
      ["rac_feet", "RAC footwear", "feet", "unique", 0],
      ["rac_upper_body", "RAC Outfit", "upper_body", "unique", 0],
  ]],
  ["binance_us_collection", "Binance US", "0xa8ee490e4c4da48cc1653502c1a77479d4d818de", [
      ["binance_us_hat", "Binance US Hat", "hat", "uncommon", 0],
      ["binance_us_upper_body", "Binance US Hoodie", "upper_body", "uncommon", 0],
  ]],
  ["dg_atari_dillon_francis", "DG × Atari × Dillon Francis", "0x51e0b1afe5da0c038fc93a3fc8e11cf7a238b40b", [
      ["gerald_patchwork_knit_sweater", "Gerald Patchwork Knit Sweater", "upper_body", "epic", 0],
      ["gerald_striped_knit_sweater", "Gerald Striped Knit Sweater", "upper_body", "epic", 0],
  ]],
  ["rtfkt_x_atari", "RTFKT × Atari", "", [
      ["p_rtfkt_x_atari_feet", "Purple RTFKT X Atari Sneakers", "feet", "epic", 0],
      ["r_rtfkt_x_atari_feet", "Red RTFKT X Atari Sneakers", "feet", "unique", 0],
  ]],
  ["winklevoss_capital", "Winklevoss Capital", "0xc82a864a94db3550bc71fcb4ce07228bcec21f1a", [
      ["winklevoss_hat", "Winklevoss Cap", "hat", "epic", 0],
      ["winklevoss_upper_body", "Winklevoss T-Shirt", "upper_body", "epic", 0],
  ]],
] as const;
