/**
 * Seating — bench circles you can actually sit on, and the poses that fit them.
 *
 * ★ THE POSE SETS THE HEIGHT, NOT THE MODEL. `scripts/emotes/build-seat-poses.ts` solves each
 * seated clip through forward kinematics until the grounded SOLE rests on the paving, and every
 * pose lands its hips within a couple of centimetres of SEAT_HIP_HEIGHT_M. The bench seat is
 * then modelled under the sitter's UNDERSIDE — see the note on BENCH_SEAT_TOP_M, which is where
 * the first version went wrong. Change a pose, re-run the script, copy the two numbers it
 * prints — never tune the bench to fix a pose.
 *
 * ★ THE AVATAR ROOT SITS UNDER THE HIPS. The clips keep the hips over the rig root and run the
 * legs forward, so `movePlayerTo` targets the seat pad's centre at ground level, not the feet.
 * A seat anchor is therefore the pad centre, and its yaw is the direction the sitter faces.
 *
 * ★ ONE PLANNER, TWO FRAMES. Like ground scatter, the layout is re-solved from the same config
 * in the Builder preview and in the scene runtime — it is never transported. Same config + same
 * plot ⇒ identical circles, so a republish does not move the benches under a returning guest.
 *
 * ★ Composer frame throughout (plot centre = 0,0). The runtime shifts by `composerToDcl`.
 */

import {
  circleHitsBox,
  makeGroundRng,
  padExclusions,
  scatterPoints,
  type GroundScatterExclusion,
} from "./ground-scatter";

/* ------------------------------------------------------------------ poses -- */

export const SEAT_POSE_IDS = [
  "seat_upright",
  "seat_lean_forward",
  "seat_ankle_cross",
  "seat_arms_back",
] as const;

export type SeatPoseId = (typeof SEAT_POSE_IDS)[number];

export const SEAT_POSE_LABELS: Record<SeatPoseId, string> = {
  seat_upright: "Upright",
  seat_lean_forward: "Elbows on knees",
  seat_ankle_cross: "Feet crossed",
  seat_arms_back: "Arms on the back",
};

/** Bundled scene emote for a pose. Played with `triggerSceneEmote({ src, loop: true })`. */
export function seatPoseEmotePath(id: SeatPoseId): string {
  return `emotes/${id}_emote.glb`;
}

/** Length of every seated clip (scripts/emotes/build-seat-poses.ts). Re-fire on this seam. */
export const SEAT_POSE_LOOP_S = 4;

/**
 * Solved hip-BONE height above the paving — the LOWEST of the four poses, which is the one the
 * bench has to fit (a pose that solves higher floats a few millimetres and nobody notices; one
 * that solves lower has the slab cutting through it).
 * ‼️ Regenerated by `npm run build:seat-poses` — copy the number it prints.
 */
export const SEAT_HIP_HEIGHT_M = 0.536;

/**
 * ★★ THE HIP BONE IS NOT THE PART THAT TOUCHES THE BENCH, AND THAT COST US A VERSION.
 * The first bench modelled its top 60 mm under the hip BONE, which on the DCL rig is 60 mm
 * ABOVE the mid-thigh line — so the slab ran through the sitter's legs and it read in-world as
 * sinking into the seat. Both numbers below are measured off the base body
 * (`output/l1-wearable-cache/.../BaseMale.glb`), not guessed:
 *
 *   hip bone y=1.000 → hip socket y=0.937               = 0.063 down
 *   hip socket      → lowest rear vertex of the pelvis  = 0.121 down
 *
 * The seated thigh's underside lands ~0.10 below the socket, i.e. 20 mm ABOVE the buttocks, so
 * modelling to the buttocks seats the guest and leaves the thighs just clear of the slab.
 */
export const HIP_SOCKET_DROP_M = 0.063;
const BUTTOCK_DROP_M = 0.121;

/** Hip BONE down to whatever the guest is sitting on. */
export const SEATED_UNDERSIDE_DROP_M = HIP_SOCKET_DROP_M + BUTTOCK_DROP_M;

/**
 * Half the thigh, front to back (BaseMale's mid-thigh measures 0.20 m across). A seated thigh
 * is horizontal, so this is how far its underside hangs below the leg bone — and therefore the
 * clearance the slab has to leave. Exported because the pose tests assert against it.
 */
export const SEATED_THIGH_HALF_M = 0.1;

/** Top face of the bench seat. Everything else about the bench hangs off this. */
export const BENCH_SEAT_TOP_M = SEAT_HIP_HEIGHT_M - SEATED_UNDERSIDE_DROP_M;

/**
 * Bench finishes. `halo` is the default — a graphite slab that appears to float on one lit
 * pedestal. `prism` is the same shape in pale backlit white, for plazas where black furniture
 * reads as a hole in the paving. `timber` is the original warm bench, kept for parks.
 */
export const SEATING_STYLE_IDS = ["halo", "prism", "timber"] as const;
export type SeatingStyleId = (typeof SEATING_STYLE_IDS)[number];

export const SEATING_STYLE_LABELS: Record<SeatingStyleId, string> = {
  halo: "Halo — graphite + light",
  prism: "Prism — pale + backlit",
  timber: "Timber — warm bench",
};

export const DEFAULT_SEAT_GLOW = "#4de1ff";

export function isSeatingStyleId(v: unknown): v is SeatingStyleId {
  return typeof v === "string" && (SEATING_STYLE_IDS as readonly string[]).includes(v);
}

export function isSeatPoseId(v: unknown): v is SeatPoseId {
  return typeof v === "string" && (SEAT_POSE_IDS as readonly string[]).includes(v);
}

/* ------------------------------------------------------------------ config -- */

/** Bench circles spread over the plot paving. Persisted on `SiteGroundConfig.seating`. */
export interface SeatingConfig {
  enabled: boolean;
  /** How many bench circles to place. Trimmed by spacing, exclusions and the plot size. */
  clusters: number;
  /** Benches per circle. Three reads as a conversation; two as a waiting room. */
  benchesPerCluster: number;
  /** Distance from the circle's centre to each bench's seat line. */
  radiusM: number;
  /** Which finish the benches and the beacon wear. */
  style: SeatingStyleId;
  /** #rrggbb of every light strip on the bench and the beacon. */
  glowColor: string;
  /** A lit beacon in the middle, so the circle reads as a place rather than stray furniture. */
  centrepiece: boolean;
  /** Keep this far clear of the plot edge. */
  edgeMarginM: number;
  /** Extra keep-out padding around every building. */
  clearanceM: number;
  /** Minimum centre-to-centre distance between two circles. */
  spacingM: number;
  /** Changing this reshuffles where the circles land without touching anything else. */
  seed: number;
  /** Poses offered on a seat, in order. The first is what a plain click plays. */
  poses: SeatPoseId[];
}

export const SEATING_MAX_CLUSTERS = 12;
export const SEATING_MAX_BENCHES_PER_CLUSTER = 6;

export function defaultSeatingConfig(): SeatingConfig {
  return {
    enabled: false,
    clusters: 3,
    benchesPerCluster: 3,
    radiusM: 2.4,
    style: "halo",
    glowColor: DEFAULT_SEAT_GLOW,
    centrepiece: true,
    edgeMarginM: 4,
    clearanceM: 2.5,
    spacingM: 14,
    seed: 1,
    poses: [...SEAT_POSE_IDS],
  };
}

function num(raw: unknown, fallback: number, lo: number, hi: number): number {
  const v = typeof raw === "number" && Number.isFinite(raw) ? raw : fallback;
  return Math.min(hi, Math.max(lo, v));
}

/** Anything that is not a #rrggbb falls back — a stray value must not paint a bench black. */
function hexColor(raw: unknown, fallback: string): string {
  return typeof raw === "string" && /^#[0-9a-fA-F]{6}$/.test(raw) ? raw.toLowerCase() : fallback;
}

/** Unknown/old shapes fall back to the default — a bad config must never brick a recipe. */
export function normalizeSeatingConfig(raw: unknown): SeatingConfig {
  const base = defaultSeatingConfig();
  if (!raw || typeof raw !== "object") return base;
  const o = raw as Record<string, unknown>;
  const poses = Array.isArray(o.poses) ? o.poses.filter(isSeatPoseId) : [];
  return {
    enabled: o.enabled === true,
    clusters: Math.round(num(o.clusters, base.clusters, 0, SEATING_MAX_CLUSTERS)),
    benchesPerCluster: Math.round(
      num(o.benchesPerCluster, base.benchesPerCluster, 1, SEATING_MAX_BENCHES_PER_CLUSTER),
    ),
    radiusM: num(o.radiusM, base.radiusM, 1.4, 12),
    style: isSeatingStyleId(o.style) ? o.style : base.style,
    glowColor: hexColor(o.glowColor, base.glowColor),
    centrepiece: o.centrepiece !== false,
    edgeMarginM: num(o.edgeMarginM, base.edgeMarginM, 0, 200),
    clearanceM: num(o.clearanceM, base.clearanceM, 0, 100),
    spacingM: num(o.spacingM, base.spacingM, 0, 200),
    seed: Math.round(num(o.seed, base.seed, 0, 1_000_000)),
    // An empty list would leave a seat with nothing to play, so it falls back to all four.
    poses: poses.length > 0 ? SEAT_POSE_IDS.filter((id) => poses.includes(id)) : [...SEAT_POSE_IDS],
  };
}

/* ---------------------------------------------------------------- geometry -- */

export const BENCH_LENGTH_M = 1.8;
export const BENCH_DEPTH_M = 0.52;
const SEAT_SLAB_THICKNESS_M = 0.07;
/**
 * ★ THE BACK IS SIZED TO THE ARMS, NOT TO A CATALOGUE. `seat_arms_back` solves its forearms to
 * y≈0.89 with the underside ~0.05 lower, so the rail's TOP goes at 0.84 and the arm lies along
 * it. Move this and that pose drapes over thin air.
 */
const BACK_TOP_M = 0.84;
const BACK_THICKNESS_M = 0.07;
/** Height of the top rail the "arms on the back" pose drapes over. */
const BACK_RAIL_M = 0.1;
export const SEATS_PER_BENCH = 3;
/** Seat anchors sit this far apart along the bench. Two avatars any closer visibly overlap. */
const SEAT_PITCH_M = 0.6;

/**
 * How far forward of the seat ANCHOR the slab still runs. Past this the sitter's legs are out
 * over the paving and may hang wherever the pose wants — the pose tests use it to decide which
 * part of a leg has to clear the seat.
 */
export const SEAT_SLAB_REACH_M = BENCH_DEPTH_M / 2 + 0.04;

/** Radius of the whole circle, for keep-out tests: bench line plus the sitter's legs. */
export function seatingClusterRadiusM(config: SeatingConfig): number {
  return config.radiusM + BENCH_DEPTH_M / 2 + 0.9;
}

export type SeatingMeshKind = "box" | "cylinder";

/**
 * One primitive of the furniture, composer-centred. Box scales are full metres; a cylinder's
 * sx/sz are its DIAMETER (the primitive itself stays at radius 0.5 — see shared/dcl-disc).
 */
export interface SeatingPiece {
  id: string;
  mesh: SeatingMeshKind;
  x: number;
  y: number;
  z: number;
  /**
   * ★ Yaw is the ONLY rotation any piece carries. A raked back would need a second axis, and
   * the two renderers disagree on handedness — the Builder preview is Three.js (right-handed),
   * the scene is DCL (left-handed), so a pitch that leans back in one leans forward in the
   * other. The back is squared off instead, with a rail on top.
   */
  yawRad: number;
  sx: number;
  sy: number;
  sz: number;
  color: string;
  roughness: number;
  metalness: number;
  /**
   * Light this piece emits. Absent = an ordinary surface. The light strips are what make a
   * bench read as furniture from somewhere else rather than a park bench with the colour
   * changed, and after dark they are the only thing that says "sit here" from across a plaza.
   */
  emissive?: string;
  emissiveIntensity?: number;
  /**
   * ★ NO PHYSICS COLLIDER, EVER — only a pointer one, and only where noted.
   * The seated avatar's capsule stands at the seat anchor, which is INSIDE the slab and just
   * in front of the back panel. A blocking collider there does not make the bench solid, it
   * makes the explorer's character controller shove the sitter out of the pose the moment they
   * land on it. Same law as the paving and the ground cover: no invisible walls on the plot.
   */
  clickable: boolean;
}

/** Where one guest sits: the avatar root goes here, at paving level, facing `yawRad`. */
export interface SeatSlot {
  id: string;
  clusterId: string;
  x: number;
  z: number;
  yawRad: number;
}

export interface SeatingCluster {
  id: string;
  x: number;
  z: number;
  pieces: SeatingPiece[];
  seats: SeatSlot[];
}

export interface SeatingPlan {
  clusters: SeatingCluster[];
  seats: SeatSlot[];
  pieces: SeatingPiece[];
  /** Every primitive is a box or a low-segment cylinder; this is the whole cost. */
  triangles: number;
}

interface Finish {
  color: string;
  roughness: number;
  metalness: number;
}

interface StylePalette {
  /** Seat slab and back slats — the surfaces a guest reads as "the seat". */
  shell: Finish;
  /** Pedestal, base and rail — the structure the seat appears to float on. */
  frame: Finish;
  /** Multiplier on every light strip, so a pale bench does not blow out. */
  glow: number;
}

const STYLE_PALETTES: Record<SeatingStyleId, StylePalette> = {
  // Graphite and light. The default: furniture that belongs to a lit-up plaza.
  halo: {
    shell: { color: "#15171d", roughness: 0.32, metalness: 0.55 },
    frame: { color: "#2b303b", roughness: 0.25, metalness: 0.85 },
    glow: 1,
  },
  // Pale, near-white, backlit. For bright plazas, where a black bench reads as a hole.
  prism: {
    shell: { color: "#e6ecf5", roughness: 0.22, metalness: 0.15 },
    frame: { color: "#aab6c8", roughness: 0.3, metalness: 0.6 },
    glow: 0.7,
  },
  // The original warm bench, kept because a park does not want a neon slab.
  timber: {
    shell: { color: "#8a6a4a", roughness: 0.85, metalness: 0 },
    frame: { color: "#33363c", roughness: 0.5, metalness: 0.5 },
    glow: 0.35,
  },
};

/** Triangles per primitive: a box is 12, a low-segment cylinder is 16 segments. */
const BOX_TRIANGLES = 12;
const CYLINDER_TRIANGLES = 16 * 4;

function rotate(x: number, z: number, yawRad: number): { x: number; z: number } {
  const s = Math.sin(yawRad);
  const c = Math.cos(yawRad);
  // Bench-local +Z is the direction the sitter faces; +X runs along the seat to their left.
  return { x: x * c + z * s, z: -x * s + z * c };
}

interface Lamp extends Finish {
  emissive: string;
  emissiveIntensity: number;
}

/** A light strip: the same primitive as everything else, just told to emit. */
function lamp(config: SeatingConfig, palette: StylePalette, intensity: number): Lamp {
  return {
    color: config.glowColor,
    roughness: 0.4,
    metalness: 0,
    emissive: config.glowColor,
    emissiveIntensity: intensity * palette.glow,
  };
}

type LocalPiece = Omit<SeatingPiece, "id" | "x" | "z" | "yawRad"> & { lx: number; lz: number };

/**
 * One bench, laid out in its own frame and then placed. Local +Z is where the sitter looks.
 *
 * ★ THE SLAB FLOATS ON ONE PEDESTAL. Four legs under the corners is the shape that made the
 * first version read as a park bench; a single centre column, a light strip under the seat and
 * a line on the paving read as something that was PUT there. It is also the cheaper shape:
 * eleven boxes, 132 triangles, no mesh, nothing baked into building.glb.
 */
function benchPieces(
  idPrefix: string,
  cx: number,
  cz: number,
  yawRad: number,
  config: SeatingConfig,
): SeatingPiece[] {
  const palette = STYLE_PALETTES[config.style];
  const seatTop = BENCH_SEAT_TOP_M;
  const slabY = seatTop - SEAT_SLAB_THICKNESS_M / 2;
  const slabBottom = seatTop - SEAT_SLAB_THICKNESS_M;
  const backZ = -BENCH_DEPTH_M / 2 + BACK_THICKNESS_M / 2;
  const finX = BENCH_LENGTH_M / 2 - 0.2;
  const baseH = 0.045;
  const pedestalH = slabBottom - baseH - 0.04;

  const local: LocalPiece[] = [
    // The seat itself.
    {
      lx: 0,
      y: slabY,
      lz: 0,
      sx: BENCH_LENGTH_M,
      sy: SEAT_SLAB_THICKNESS_M,
      sz: BENCH_DEPTH_M,
      mesh: "box",
      clickable: true,
      ...palette.shell,
    },
    // Light under the slab — the gap between this and the seat is what makes it look to float.
    {
      lx: 0,
      y: slabBottom - 0.032,
      lz: 0,
      sx: BENCH_LENGTH_M - 0.2,
      sy: 0.026,
      sz: BENCH_DEPTH_M - 0.14,
      mesh: "box",
      clickable: false,
      ...lamp(config, palette, 1.5),
    },
    // Single centre pedestal.
    {
      lx: 0,
      y: baseH + pedestalH / 2,
      lz: 0,
      sx: 0.34,
      sy: pedestalH,
      sz: 0.26,
      mesh: "box",
      clickable: true,
      ...palette.frame,
    },
    // Foot plate.
    {
      lx: 0,
      y: baseH / 2,
      lz: 0,
      sx: 0.66,
      sy: baseH,
      sz: 0.42,
      mesh: "box",
      clickable: true,
      ...palette.frame,
    },
    // A line of light on the paving, so the bench still has a footprint after dark.
    {
      lx: 0,
      y: 0.006,
      lz: 0,
      sx: BENCH_LENGTH_M - 0.86,
      sy: 0.012,
      sz: 0.055,
      mesh: "box",
      clickable: false,
      ...lamp(config, palette, 0.85),
    },
    // Two back fins instead of a full panel: the back reads as structure, not a wall.
    ...[-finX, finX].map((lx) => ({
      lx,
      y: seatTop + (BACK_TOP_M - seatTop) / 2,
      lz: backZ,
      sx: 0.065,
      sy: BACK_TOP_M - seatTop,
      sz: 0.09,
      mesh: "box" as const,
      clickable: true,
      ...palette.frame,
    })),
    // Two slats across them.
    ...[0.6, 0.715].map((y) => ({
      lx: 0,
      y,
      lz: backZ,
      sx: BENCH_LENGTH_M - 0.14,
      sy: 0.075,
      sz: BACK_THICKNESS_M / 2,
      mesh: "box" as const,
      clickable: true,
      ...palette.shell,
    })),
    // Top rail: what "arms on the back" rests on, and a second light line at arm height.
    {
      lx: 0,
      y: BACK_TOP_M - BACK_RAIL_M / 2,
      lz: backZ,
      sx: BENCH_LENGTH_M,
      sy: BACK_RAIL_M,
      sz: BACK_THICKNESS_M + 0.06,
      mesh: "box",
      clickable: true,
      ...palette.frame,
    },
    {
      lx: 0,
      y: BACK_TOP_M - BACK_RAIL_M - 0.012,
      lz: backZ,
      sx: BENCH_LENGTH_M - 0.1,
      sy: 0.018,
      sz: BACK_THICKNESS_M + 0.07,
      mesh: "box",
      clickable: false,
      ...lamp(config, palette, 1.1),
    },
  ];

  return local.map((p, i) => {
    const w = rotate(p.lx, p.lz, yawRad);
    return {
      id: `${idPrefix}_p${i}`,
      mesh: p.mesh,
      x: cx + w.x,
      y: p.y,
      z: cz + w.z,
      yawRad,
      sx: p.sx,
      sy: p.sy,
      sz: p.sz,
      color: p.color,
      roughness: p.roughness,
      metalness: p.metalness,
      ...(p.emissive ? { emissive: p.emissive, emissiveIntensity: p.emissiveIntensity } : {}),
      clickable: p.clickable,
    };
  });
}

/**
 * Seat anchors along one bench. The anchor is the pad centre — the avatar root goes there and
 * the seated legs run forward from it, which is exactly how the clips are authored.
 */
function benchSeats(idPrefix: string, clusterId: string, cx: number, cz: number, yawRad: number): SeatSlot[] {
  const out: SeatSlot[] = [];
  const first = -((SEATS_PER_BENCH - 1) / 2) * SEAT_PITCH_M;
  for (let i = 0; i < SEATS_PER_BENCH; i += 1) {
    // Sit a touch back of the pad centre: the hips belong over the rear half of the seat.
    const w = rotate(first + i * SEAT_PITCH_M, -0.04, yawRad);
    out.push({ id: `${idPrefix}_s${i}`, clusterId, x: cx + w.x, z: cz + w.z, yawRad });
  }
  return out;
}

/**
 * What stands in the middle of the circle.
 *
 * ★ A FLAT DISC IS NOT A CENTREPIECE. The first version was one squat cylinder, which in a dark
 * district renders as a black hole in the paving — "just a black circle". A ring of benches
 * needs something with HEIGHT at its focus, or it reads as three pieces of furniture that
 * happen to face each other. This is a beacon: a halo burnt into the paving, a plinth, a mast,
 * and a lantern floating clear of it.
 */
function centrepiecePieces(
  id: string,
  centreX: number,
  centreZ: number,
  config: SeatingConfig,
): SeatingPiece[] {
  const palette = STYLE_PALETTES[config.style];
  const at = (
    suffix: string,
    mesh: SeatingMeshKind,
    y: number,
    diameter: number,
    height: number,
    finish: Finish | Lamp,
    yawRad = 0,
  ): SeatingPiece => ({
    id: `${id}_hub_${suffix}`,
    mesh,
    x: centreX,
    y,
    z: centreZ,
    yawRad,
    sx: diameter,
    sy: height,
    sz: diameter,
    clickable: false,
    ...finish,
  });

  return [
    // Halo on the paving: the ring is what turns three benches into one place.
    at("halo", "cylinder", 0.005, config.radiusM * 1.12, 0.01, lamp(config, palette, 0.6)),
    at("plinth", "cylinder", 0.055, config.radiusM * 0.58, 0.11, palette.frame),
    at("disc", "cylinder", 0.118, config.radiusM * 0.46, 0.016, lamp(config, palette, 1.2)),
    at("mast", "box", 0.42, 0.12, 0.58, palette.frame),
    // Floating lantern, turned 45° so it catches the light on a corner instead of a face.
    at("lantern", "box", 0.86, 0.24, 0.24, lamp(config, palette, 1.8), Math.PI / 4),
  ];
}

/** One circle of benches, all facing the middle. */
export function seatingCluster(
  id: string,
  centreX: number,
  centreZ: number,
  spinRad: number,
  config: SeatingConfig,
): SeatingCluster {
  const pieces: SeatingPiece[] = [];
  const seats: SeatSlot[] = [];
  const n = Math.max(1, Math.round(config.benchesPerCluster));

  for (let i = 0; i < n; i += 1) {
    const theta = spinRad + (i / n) * Math.PI * 2;
    const bx = centreX + Math.sin(theta) * config.radiusM;
    const bz = centreZ + Math.cos(theta) * config.radiusM;
    // Facing the middle: the bench's local +Z points back at the centre.
    const yaw = theta + Math.PI;
    const prefix = `${id}_b${i}`;
    pieces.push(...benchPieces(prefix, bx, bz, yaw, config));
    seats.push(...benchSeats(prefix, id, bx, bz, yaw));
  }

  if (config.centrepiece) pieces.push(...centrepiecePieces(id, centreX, centreZ, config));

  return { id, x: centreX, z: centreZ, pieces, seats };
}


/**
 * Plan every circle on the plot. Deterministic from config + plot size, exactly like ground
 * scatter — the Builder preview and the scene runtime call this and get the same field.
 */
export function planSeating(args: {
  width: number;
  depth: number;
  config: SeatingConfig;
  exclusions?: readonly GroundScatterExclusion[];
}): SeatingPlan {
  const config = args.config;
  const empty: SeatingPlan = { clusters: [], seats: [], pieces: [], triangles: 0 };
  if (!config.enabled || config.clusters <= 0) return empty;

  const width = Math.max(0, args.width);
  const depth = Math.max(0, args.depth);
  const radius = seatingClusterRadiusM(config);
  const rng = makeGroundRng(`seating:${config.seed}`, width, depth);
  const points = scatterPoints({
    rng,
    count: Math.min(config.clusters, SEATING_MAX_CLUSTERS),
    halfW: width / 2 - config.edgeMarginM,
    halfD: depth / 2 - config.edgeMarginM,
    radius,
    minDist: Math.max(config.spacingM, radius * 2),
    exclusions: padExclusions(args.exclusions ?? [], config.clearanceM),
  });

  const clusters = points.map((p, i) => seatingCluster(`sc${i}`, p.x, p.z, rng() * Math.PI * 2, config));
  const pieces = clusters.flatMap((c) => c.pieces);
  return {
    clusters,
    seats: clusters.flatMap((c) => c.seats),
    pieces,
    triangles: pieces.reduce((n, p) => n + (p.mesh === "cylinder" ? CYLINDER_TRIANGLES : BOX_TRIANGLES), 0),
  };
}

/** True when a circle would land on top of a keep-out box. Exposed for the preview's warnings. */
export function seatingClusterBlocked(
  cluster: SeatingCluster,
  config: SeatingConfig,
  exclusions: readonly GroundScatterExclusion[],
): boolean {
  return exclusions.some((box) => circleHitsBox({ x: cluster.x, z: cluster.z }, seatingClusterRadiusM(config), box));
}
